// Generated by CoffeeScript 1.6.1
(function() {

  require('../index')(function(fwords) {
    var func, key, lang, words, _results;
    _results = [];
    for (lang in fwords) {
      func = fwords[lang];
      _results.push((function() {
        var _results1;
        _results1 = [];
        for (key in func) {
          words = func[key];
          _results1.push(console.log([lang, key].join('.'), "contains", words.length, "words"));
        }
        return _results1;
      })());
    }
    return _results;
  });

}).call(this);
