// Generated by CoffeeScript 1.6.1
(function() {

  require('../index')(function(fwords) {
    var func, key, lang, words;
    for (lang in fwords) {
      func = fwords[lang];
      if (typeof func === 'object') {
        for (key in func) {
          words = func[key];
          console.log([lang, key].join('.'), "contains", words.length, "words");
        }
        console.log("`" + lang + "` contains " + (fwords.total(lang).length) + " fwords");
      }
    }
    return console.log("In total, " + (fwords.total().length) + " fwords");
  });

}).call(this);
